services:
  mongodb:
    image: mongo
    networks:
    - fav-net
    volumes:
    - "mongo-configdb:/data/configdb"
    - "mongodb:/data/db"

  fav-api:
    build: ./
    #image: fav-api
    restart: on-failure:10
    networks:
    - fav-net
    ports:
    - '3000:3000'
    depends_on:
    - mongodb

volumes:
  mongodb:
    external: true
    name: mongodb
  mongo-configdb:
    external: true
    name: mongo-configdb
  
networks:
  fav-net: 

